name: Set Version
description: Set version for the project

inputs:
  target: 
    description: 'Target to set version'
    required: true
    default: 'src/ConfigParam.h'
  version_str: 
    description: 'Version string to set'
    required: true
    default: '0.0.0'
  version_str_size: 
    required: false
    default: 16
runs:
  using: 'node16'
  main: 'index.js'
